<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class IdiomsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $idioms = [
            [
                'english_phrase' => 'I have to pee',
                'turkish_translation' => 'çok tuvaletim geldi',
                'example_sentence_1' => 'I have to pee—can we take a quick break?',
                'example_sentence_2' => 'I have to pee so badly, I can\'t wait any longer!',
                'image_path' => 'idioms/gorsel1.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'sit tight',
                'turkish_translation' => 'sabırlı ol',
                'example_sentence_1' => 'Sit tight, the results will be announced soon.',
                'example_sentence_2' => 'Sit tight, I\'ll be back in a minute.',
                'image_path' => 'idioms/gorsel2.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'the wheels come off',
                'turkish_translation' => 'işler sarpa sardı',
                'example_sentence_1' => 'Everything was fine until the wheels came off during the meeting.',
                'example_sentence_2' => 'Everything went wrong—it was like the wheels came off.',
                'image_path' => 'idioms/gorsel3.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'even monkeys fall from tree',
                'turkish_translation' => 'herkes hata yapar',
                'example_sentence_1' => 'Don\'t worry about the mistake—even monkeys fall from trees.',
                'example_sentence_2' => 'Don\'t be too hard on yourself—even monkeys fall from trees.',
                'image_path' => 'idioms/gorsel4.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'let the good times roll!',
                'turkish_translation' => 'en kötü günümüz böyle olsun',
                'example_sentence_1' => 'The exams are over, so let the good times roll!',
                'example_sentence_2' => 'We\'re on vacation, so let the good times roll!',
                'image_path' => 'idioms/gorsel5.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'the grass is always greener on the other side',
                'turkish_translation' => 'davulun sesi uzaktan hoş gelir',
                'example_sentence_1' => 'He wants a new job, but the grass is always greener on the other side.',
                'example_sentence_2' => 'She moved to another city thinking it would be better—the grass is always greener on the other side.',
                'image_path' => 'idioms/gorsel6.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'barking dog never bites',
                'turkish_translation' => 'havlayan köpek ısırmaz',
                'example_sentence_1' => 'He talks a lot, but a barking dog never bites.',
                'example_sentence_2' => 'He acts tough, but a barking dog never bites.',
                'image_path' => 'idioms/gorsel7.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'go with the flow',
                'turkish_translation' => 'akışına bırakmak',
                'example_sentence_1' => 'There\'s no plan—just go with the flow.',
                'example_sentence_2' => 'Don\'t stress, just go with the flow.',
                'image_path' => 'idioms/gorsel8.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'are you pulling my leg?',
                'turkish_translation' => 'benimle dalgamı geçiyorsun?',
                'example_sentence_1' => 'Are you pulling my leg, or is this real?',
                'example_sentence_2' => 'You bought a car for $1? Are you pulling my leg?',
                'image_path' => 'idioms/gorsel9.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'throw in the towel',
                'turkish_translation' => 'havlu atmak',
                'example_sentence_1' => 'After failing three times, he decided to throw in the towel.',
                'example_sentence_2' => 'After years of trying, he finally threw in the towel.',
                'image_path' => 'idioms/gorsel10.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'keep your eyes peeled',
                'turkish_translation' => 'gözünü dört aç',
                'example_sentence_1' => 'Keep your eyes peeled for the red car.',
                'example_sentence_2' => 'Keep your eyes peeled for the exit sign.',
                'image_path' => 'idioms/gorsel11.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'let the cat out of the bag',
                'turkish_translation' => 'ağzındaki baklayı çıkar',
                'example_sentence_1' => 'She let the cat out of the bag about the surprise party.',
                'example_sentence_2' => 'He let the cat out of the bag and ruined the surprise.',
                'image_path' => 'idioms/gorsel12.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'no ifs and buts',
                'turkish_translation' => 'lamı cimi yok',
                'example_sentence_1' => 'You have to do it—no ifs and buts!',
                'example_sentence_2' => 'You\'re coming with us—no ifs and buts!',
                'image_path' => 'idioms/gorsel13.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'The shoemaker\'s children go barefoot',
                'turkish_translation' => 'terzi kendi söküğünü dikemezmiş',
                'example_sentence_1' => 'She\'s a great teacher, but her own kids struggle—shoemaker\'s children go barefoot.',
                'example_sentence_2' => 'His car is falling apart—looks like the shoemaker\'s children go barefoot.',
                'image_path' => 'idioms/gorsel14.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'be lost at sea',
                'turkish_translation' => 'kafası karışmak',
                'example_sentence_1' => 'I\'m completely lost at sea with this new software.',
                'example_sentence_2' => 'I\'m completely be lost at sea with these new rules.',
                'image_path' => 'idioms/gorsel15.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'find your feet',
                'turkish_translation' => 'ayak uydurmak,uydurmaya çalışmak',
                'example_sentence_1' => 'It took a few weeks, but I finally found my feet at the new job.',
                'example_sentence_2' => 'It took her a few weeks to find her feet at her new school.',
                'image_path' => 'idioms/gorsel16.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'get your nose out of my business !',
                'turkish_translation' => 'İşime burnunu sokma !',
                'example_sentence_1' => 'Hey, get your nose out of my business!',
                'example_sentence_2' => 'Mind your own business and get your nose out of mine!',
                'image_path' => 'idioms/gorsel17.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I smell a rat',
                'turkish_translation' => 'Bu işte bir iş var/ Burnuma kötü kokular geliyor',
                'example_sentence_1' => 'I smell a rat—something doesn\'t feel right here.',
                'example_sentence_2' => 'I smell a rat—someone\'s lying.',
                'image_path' => 'idioms/gorsel18.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'down to earth',
                'turkish_translation' => 'ayakları yere basmak',
                'example_sentence_1' => 'He\'s rich but very down to earth.',
                'example_sentence_2' => 'She may be famous, but she\'s really down to earth.',
                'image_path' => 'idioms/gorsel19.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'save your breath!',
                'turkish_translation' => 'nefesini boşa tüketme!',
                'example_sentence_1' => 'Save your breath—he never listens anyway.',
                'example_sentence_2' => 'Save your breath—he won\'t change his mind.',
                'image_path' => 'idioms/gorsel20.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'what goes around comes around',
                'turkish_translation' => 'ne ekersen onu biçersin',
                'example_sentence_1' => 'He was rude to everyone, and now no one helps him—what goes around comes around.',
                'example_sentence_2' => 'He was mean to everyone, and now he\'s alone—what goes around comes around.',
                'image_path' => 'idioms/gorsel21.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'higher than a cat\'s back',
                'turkish_translation' => 'aşırı pahalı',
                'example_sentence_1' => 'After her promotion, she was walking around higher than a cat\'s back.',
                'example_sentence_2' => 'She acted higher than a cat\'s back after getting the award.',
                'image_path' => 'idioms/gorsel22.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'this is how it works',
                'turkish_translation' => 'bu işler böyle yürür',
                'example_sentence_1' => 'First, turn it on—this is how it works.',
                'example_sentence_2' => 'Just click this button—this is how it works.',
                'image_path' => 'idioms/gorsel23.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I\'m history!',
                'turkish_translation' => 'kaçtım/ hadi ben kaçtım!',
                'example_sentence_1' => 'I\'m history—time to head home!',
                'example_sentence_2' => 'Okay, I\'m done—I\'m history!',
                'image_path' => 'idioms/gorsel24.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I have to much on my plate.',
                'turkish_translation' => 'İşim başımdan aşkın',
                'example_sentence_1' => 'I can\'t take more tasks—I have too much on my plate.',
                'example_sentence_2' => 'I can\'t help this weekend—I have too much on my plate.',
                'image_path' => 'idioms/gorsel25.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'too much of anything is good for nothing',
                'turkish_translation' => 'her şeyin fazlası zarar',
                'example_sentence_1' => 'Too much of anything is good for nothing.',
                'example_sentence_2' => 'Too much of anything is good for nothing, even chocolate!',
                'image_path' => 'idioms/gorsel26.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'It is not rocket science',
                'turkish_translation' => 'atla deve değil',
                'example_sentence_1' => 'Don\'t panic, it\'s not rocket science.',
                'example_sentence_2' => 'Come on, you can do this—it\'s not rocket science.',
                'image_path' => 'idioms/gorsel27.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'are you nuts or what?',
                'turkish_translation' => 'Deli misin nesin?',
                'example_sentence_1' => 'Are you nuts or what? That idea is wild!',
                'example_sentence_2' => 'Are you nuts or what? That\'s dangerous!',
                'image_path' => 'idioms/gorsel28.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'hit the books',
                'turkish_translation' => 'ineklemek/ çok çalışmak',
                'example_sentence_1' => 'I have to hit the books if I want to pass tomorrow\'s test.',
                'example_sentence_2' => 'I need to hit the books if I want to pass the exam.',
                'image_path' => 'idioms/gorsel29.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'mr.know it all!',
                'turkish_translation' => 'çok bilmiş',
                'example_sentence_1' => 'Stop acting like a Mr. Know-it-all—no one likes that.',
                'example_sentence_2' => 'Stop being such a Mr. Know-it-all and listen to others for once.',
                'image_path' => 'idioms/gorsel30.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I lost track of time',
                'turkish_translation' => 'zamanın nasıl geçtiğini anlamadım',
                'example_sentence_1' => 'Sorry I\'m late, I lost track of time.',
                'example_sentence_2' => 'I was so focused on the game that I lost track of time.',
                'image_path' => 'idioms/gorsel31.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'There is no rose without a thorn',
                'turkish_translation' => 'Gülü seven dikenine katlanır.',
                'example_sentence_1' => 'She\'s beautiful, but there is no rose without a thorn.',
                'example_sentence_2' => 'He\'s kind, but remember—there is no rose without a thorn.',
                'image_path' => 'idioms/gorsel32.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Like taking candy from a baby',
                'turkish_translation' => 'Tereyağından kıl çeker gibi',
                'example_sentence_1' => 'That test was so easy—it was like taking candy from a baby.',
                'example_sentence_2' => 'Beating him at chess was like taking candy from a baby.',
                'image_path' => 'idioms/gorsel33.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I am at the end of my rope',
                'turkish_translation' => 'Sabrım taşmak üzere',
                'example_sentence_1' => 'I\'m at the end of my rope with this noisy neighbor.',
                'example_sentence_2' => 'I\'m at the end of my rope trying to fix this old computer.',
                'image_path' => 'idioms/gorsel34.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'That\'s music to my ears',
                'turkish_translation' => 'Bunu duymak güzel',
                'example_sentence_1' => 'Your kind words are music to my ears.',
                'example_sentence_2' => 'Hearing my favorite song on the radio was music to my ears.',
                'image_path' => 'idioms/gorsel35.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'act your wage',
                'turkish_translation' => 'ayağını yorganına göre uzat',
                'example_sentence_1' => 'If you can\'t afford it, act your wage.',
                'example_sentence_2' => 'You can\'t afford that vacation—act your wage!',
                'image_path' => 'idioms/gorsel36.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'What have you been smoking?',
                'turkish_translation' => 'Neyin kafasını yaşıyorsun sen?',
                'example_sentence_1' => 'That idea is so crazy—what have you been smoking?',
                'example_sentence_2' => 'Come on, what have you been smoking to think that\'s a good idea?',
                'image_path' => 'idioms/gorsel37.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I love you to the moon and back',
                'turkish_translation' => 'Seni çokkkkk seviyorum',
                'example_sentence_1' => 'I love you to the moon and back.',
                'example_sentence_2' => 'My daughter always says, "I love you to the moon and back."',
                'image_path' => 'idioms/gorsel38.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'never say die!',
                'turkish_translation' => 'Asla pes etme!',
                'example_sentence_1' => 'Never say die! We still have a chance.',
                'example_sentence_2' => 'Even when things go wrong, she says, "never say die!"',
                'image_path' => 'idioms/gorsel39.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'The cupboard is bare',
                'turkish_translation' => 'Tam takır kuru bakır',
                'example_sentence_1' => 'We need to buy food—the cupboard is bare.',
                'example_sentence_2' => 'There\'s nothing to cook—the cupboard is completely bare.',
                'image_path' => 'idioms/gorsel40.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Search me !',
                'turkish_translation' => 'Nerden bileyim ben!',
                'example_sentence_1' => 'Search me! I have no idea what happened.',
                'example_sentence_2' => 'Search me, I didn\'t touch your phone.',
                'image_path' => 'idioms/gorsel41.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'too many cooks spoil the broth',
                'turkish_translation' => 'horozu çok olan köyde sabah geç olur',
                'example_sentence_1' => 'Too many cooks spoil the broth in this project.',
                'example_sentence_2' => 'They all wanted to be in charge—too many cooks spoiled the broth.',
                'image_path' => 'idioms/gorsel42.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I could see it coming',
                'turkish_translation' => 'böyle olacağı belliydi',
                'example_sentence_1' => 'I wasn\'t surprised—I could see it coming.',
                'example_sentence_2' => 'When he didn\'t show up, I could see it coming.',
                'image_path' => 'idioms/gorsel43.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Let\'s call it a day!',
                'turkish_translation' => 'Bugünlük bu kadar yeter',
                'example_sentence_1' => 'It\'s been a long day; let\'s call it a day.',
                'example_sentence_2' => 'We\'ve done enough today—let\'s call it a day.',
                'image_path' => 'idioms/gorsel44.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Rome wasn\'t built in a day',
                'turkish_translation' => 'Roma bir günde inşa edilmedi/ Kolay olmadı buralara gelmek',
                'example_sentence_1' => 'Be patient—Rome wasn\'t built in a day.',
                'example_sentence_2' => 'Learning takes time—Rome wasn\'t built in a day.',
                'image_path' => 'idioms/gorsel45.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Has the cat got your tongue?',
                'turkish_translation' => 'Dilini mi yuttun?',
                'example_sentence_1' => 'Why are you so quiet? Has the cat got your tongue?',
                'example_sentence_2' => 'Why so silent? Has the cat got your tongue?',
                'image_path' => 'idioms/gorsel46.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Better late than never',
                'turkish_translation' => 'Geç olsun güç olmasın',
                'example_sentence_1' => 'He finally showed up—better late than never.',
                'example_sentence_2' => 'He forgot my birthday, but better late than never.',
                'image_path' => 'idioms/gorsel47.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Easy peasy right?',
                'turkish_translation' => 'Çocuk oyuncağı değil mi?',
                'example_sentence_1' => 'This quiz is easy peasy, right?',
                'example_sentence_2' => 'Don\'t worry about this test—it\'s easy peasy.',
                'image_path' => 'idioms/gorsel48.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'No pain no gain',
                'turkish_translation' => 'Emeksiz yemek olmaz',
                'example_sentence_1' => 'If you want results, remember: no pain no gain.',
                'example_sentence_2' => 'She trains every morning—no pain, no gain!',
                'image_path' => 'idioms/gorsel49.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'cost an arm and a leg',
                'turkish_translation' => 'Çok pahalıya mal olmak',
                'example_sentence_1' => 'That designer bag costs an arm and a leg.',
                'example_sentence_2' => 'That car is beautiful, but it cost him an arm and a leg.',
                'image_path' => 'idioms/gorsel50.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'once in a blue moon',
                'turkish_translation' => 'Kırk yılda bir',
                'example_sentence_1' => 'I only see her once in a blue moon.',
                'example_sentence_2' => 'We have dinner together once in a blue moon.',
                'image_path' => 'idioms/gorsel51.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'It is raining cats and dogs',
                'turkish_translation' => 'Bardaktan boşalırcasına yağmur yağıyor',
                'example_sentence_1' => 'Don\'t forget your umbrella—it\'s raining cats and dogs!',
                'example_sentence_2' => 'It\'s raining cats and dogs, so let\'s stay indoors.',
                'image_path' => 'idioms/gorsel52.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Hit the sack',
                'turkish_translation' => 'Kafayı yastığa koymak',
                'example_sentence_1' => 'I\'m exhausted; I\'m going to hit the sack.',
                'example_sentence_2' => 'After a long day, I just want to hit the sack.',
                'image_path' => 'idioms/gorsel53.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'miss the boat',
                'turkish_translation' => 'fırsatı kaçırmak',
                'example_sentence_1' => 'He missed the boat and didn\'t get the job.',
                'example_sentence_2' => 'He missed the boat on investing early.',
                'image_path' => 'idioms/gorsel54.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'when pigs fly',
                'turkish_translation' => 'imkansız /hayatta olmaz',
                'example_sentence_1' => 'Sure, he\'ll clean his room… when pigs fly.',
                'example_sentence_2' => 'You\'ll see him do chores when pigs fly.',
                'image_path' => 'idioms/gorsel55.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'every dog has his day',
                'turkish_translation' => 'herkesin yüzü bir gün güler/Şans herkese bir gün güler',
                'example_sentence_1' => 'Don\'t give up—every dog has his day.',
                'example_sentence_2' => 'Be patient—every dog has his day.',
                'image_path' => 'idioms/gorsel56.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Go dutch',
                'turkish_translation' => 'Alman usulü/ hadi alman usulü yapalım',
                'example_sentence_1' => 'Let\'s go dutch and split the bill.',
                'example_sentence_2' => 'On our trip, we went dutch every time.',
                'image_path' => 'idioms/gorsel57.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'chasing rainbows',
                'turkish_translation' => 'İmkansız bir şey için çabalamak',
                'example_sentence_1' => 'He\'s always chasing rainbows instead of being realistic.',
                'example_sentence_2' => 'He keeps chasing rainbows instead of working hard.',
                'image_path' => 'idioms/gorsel58.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'not lift a finger',
                'turkish_translation' => 'kılını bile kıpırdatmamak',
                'example_sentence_1' => 'She won\'t lift a finger to help.',
                'example_sentence_2' => 'I cleaned everything, but she didn\'t lift a finger.',
                'image_path' => 'idioms/gorsel59.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'dirt cheap',
                'turkish_translation' => 'sudan ucuz',
                'example_sentence_1' => 'This phone was dirt cheap at the market.',
                'example_sentence_2' => 'I got this jacket dirt cheap at the flea market.',
                'image_path' => 'idioms/gorsel60.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'don\'t push your luck!',
                'turkish_translation' => 'Şansını zorlama!',
                'example_sentence_1' => 'You already won twice—don\'t push your luck!',
                'example_sentence_2' => 'You\'re lucky today—don\'t push your luck!',
                'image_path' => 'idioms/gorsel61.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'pain in the neck',
                'turkish_translation' => 'baş belası /sorun çıkaran kimse',
                'example_sentence_1' => 'This homework is a real pain in the neck.',
                'example_sentence_2' => 'This waiting is a real pain in the neck.',
                'image_path' => 'idioms/gorsel62.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'nail it',
                'turkish_translation' => 'başarmak',
                'example_sentence_1' => 'You practiced a lot—you\'ll nail it!',
                'example_sentence_2' => 'You practiced all week—go out there and nail it!',
                'image_path' => 'idioms/gorsel63.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'speak of the devil',
                'turkish_translation' => 'iyi insan lafının üzerine gelir/ iti an çomağını hazırla',
                'example_sentence_1' => 'Speak of the devil! We were just talking about you.',
                'example_sentence_2' => 'Oh look, speak of the devil—here she comes!',
                'image_path' => 'idioms/gorsel64.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'the last strow',
                'turkish_translation' => 'bardağı taşıran son damla',
                'example_sentence_1' => 'That rude comment was the last straw for me.',
                'example_sentence_2' => 'That comment was really the last straw for me.',
                'image_path' => 'idioms/gorsel65.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'break the ice',
                'turkish_translation' => 'ortamı yumuşatmak',
                'example_sentence_1' => 'She told a joke to break the ice.',
                'example_sentence_2' => 'I always tell a fun fact to break the ice.',
                'image_path' => 'idioms/gorsel66.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'a perfect storm',
                'turkish_translation' => 'her şeyin üst üste gelmesi',
                'example_sentence_1' => 'It was a perfect storm of bad luck.',
                'example_sentence_2' => 'The power outage and traffic made it a perfect storm.',
                'image_path' => 'idioms/gorsel67.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Don\'t put all your eggs in one basket',
                'turkish_translation' => 'tek bir şeye bel bağlama',
                'example_sentence_1' => 'Don\'t put all your eggs in one basket.',
                'example_sentence_2' => 'I invested in two things—I didn\'t put all my eggs in one basket.',
                'image_path' => 'idioms/gorsel68.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Actions speak louder than words',
                'turkish_translation' => 'lafa değil icraate bak',
                'example_sentence_1' => 'Actions speak louder than words.',
                'example_sentence_2' => 'He talks a lot, but actions speak louder than words.',
                'image_path' => 'idioms/gorsel69.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'It\'s on me!',
                'turkish_translation' => 'Benden olsun, Ben ısmarlıyorum',
                'example_sentence_1' => 'Lunch? It\'s on me!',
                'example_sentence_2' => 'Don\'t worry about paying—it\'s on me.',
                'image_path' => 'idioms/gorsel70.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'I am under the weather.',
                'turkish_translation' => 'Modum yok/Keyifsizim/Hastayım',
                'example_sentence_1' => 'I\'m staying home today—I\'m under the weather.',
                'example_sentence_2' => 'I didn\'t go to school today because I\'m under the weather.',
                'image_path' => 'idioms/gorsel71.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'You have my word!',
                'turkish_translation' => 'Sana söz veriyorum( I promise you)',
                'example_sentence_1' => 'You have my word—I\'ll be there.',
                'example_sentence_2' => 'You have my word—I\'ll keep the secret.',
                'image_path' => 'idioms/gorsel72.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Save for a rainy day',
                'turkish_translation' => 'ak akçe kara gün içindir',
                'example_sentence_1' => 'She always saves money for a rainy day.',
                'example_sentence_2' => 'She puts money aside to save for a rainy day.',
                'image_path' => 'idioms/gorsel73.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'It\'s your turn! / The ball is in your court',
                'turkish_translation' => 'Sıra sende! / Sıra senin !',
                'example_sentence_1' => 'It\'s your turn—the ball is in your court.',
                'example_sentence_2' => 'It\'s your turn to wash the dishes—the ball is in your court!',
                'image_path' => 'idioms/gorsel74.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Ignorance is bliss',
                'turkish_translation' => 'Cehalet mutluluktur.',
                'example_sentence_1' => 'Don\'t overthink—sometimes ignorance is bliss.',
                'example_sentence_2' => 'She didn\'t want to know—sometimes ignorance is bliss.',
                'image_path' => 'idioms/gorsel75.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Don\'t count your chickens before they hatch',
                'turkish_translation' => 'Dereyi görmeden paçayı sıvama',
                'example_sentence_1' => 'Don\'t count your chickens before they hatch.',
                'example_sentence_2' => 'Don\'t count your chickens before they hatch—wait for the results.',
                'image_path' => 'idioms/gorsel76.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'The lights are on, but nobody\'s home',
                'turkish_translation' => 'aklı bir karış havada/ kendi burada aklı yok',
                'example_sentence_1' => 'He\'s awake, but the lights are on and nobody\'s home.',
                'example_sentence_2' => 'He looked awake, but the lights were on and nobody was home.',
                'image_path' => 'idioms/gorsel77.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Hold your horses',
                'turkish_translation' => 'Ağır ol/ Bekle biraz !',
                'example_sentence_1' => 'Hold your horses—we\'re not ready yet!',
                'example_sentence_2' => 'Hold your horses! We\'re not leaving yet.',
                'image_path' => 'idioms/gorsel78.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Running around like a headless chicken',
                'turkish_translation' => 'Danalar gibi konuşmak / Deli dana gibi koşuşturmak',
                'example_sentence_1' => 'She\'s running around like a headless chicken today.',
                'example_sentence_2' => 'Before the party, she was running around like a headless chicken.',
                'image_path' => 'idioms/gorsel79.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'bull in a china shop',
                'turkish_translation' => 'Beceriksiz / Çok sakar',
                'example_sentence_1' => 'He walks like a bull in a china shop.',
                'example_sentence_2' => 'He knocked over everything—like a bull in a china shop.',
                'image_path' => 'idioms/gorsel80.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'go bananas',
                'turkish_translation' => 'keçileri kaçırmak',
                'example_sentence_1' => 'The kids went bananas at the birthday party.',
                'example_sentence_2' => 'The kids go bananas every time they see balloons.',
                'image_path' => 'idioms/gorsel81.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Drinking like a fish',
                'turkish_translation' => 'Sünger gibi içmek/ Sarhoş olmak',
                'example_sentence_1' => 'He\'s drinking like a fish again.',
                'example_sentence_2' => 'He drank three sodas—he\'s drinking like a fish!',
                'image_path' => 'idioms/gorsel82.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Bite the bullet',
                'turkish_translation' => 'Dişini sıkmak',
                'example_sentence_1' => 'I finally bit the bullet and called the dentist.',
                'example_sentence_2' => 'I didn\'t want to go, but I bit the bullet and did it.',
                'image_path' => 'idioms/gorsel83.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Through thick and thin',
                'turkish_translation' => 'İyi günde kötü günde',
                'example_sentence_1' => 'I\'ll support you through thick and thin.',
                'example_sentence_2' => 'My best friend has been with me through thick and thin.',
                'image_path' => 'idioms/gorsel84.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'It\'s the best thing since sliced bread',
                'turkish_translation' => 'Harika,muhteşem',
                'example_sentence_1' => 'This gadget is the best thing since sliced bread.',
                'example_sentence_2' => 'That new blender is the best thing since sliced bread!',
                'image_path' => 'idioms/gorsel85.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Come rain or shine',
                'turkish_translation' => 'Ne olursa olsun',
                'example_sentence_1' => 'We\'ll be there, come rain or shine.',
                'example_sentence_2' => 'We\'ll go to the park, come rain or shine.',
                'image_path' => 'idioms/gorsel86.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'You can say that again',
                'turkish_translation' => 'Doğru söyledin/ Sana katılıyorum',
                'example_sentence_1' => '"That was amazing!" — "You can say that again!"',
                'example_sentence_2' => '"Pizza again?" — "You can say that again!"',
                'image_path' => 'idioms/gorsel87.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Kill two birds with one stone',
                'turkish_translation' => 'Bir taşla iki kuş vurmak',
                'example_sentence_1' => 'I cleaned the house and cooked—killed two birds with one stone.',
                'example_sentence_2' => 'I answered emails and cleaned my desk—killed two birds with one stone.',
                'image_path' => 'idioms/gorsel88.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Adding fuel to the fire',
                'turkish_translation' => 'Yangına körükle gitmek',
                'example_sentence_1' => 'Yelling back only added fuel to the fire.',
                'example_sentence_2' => 'Arguing with him only added fuel to the fire.',
                'image_path' => 'idioms/gorsel89.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Let sleeping dogs lie',
                'turkish_translation' => 'Eskileri kurcalamayalım/ Geçmiş geçmişte kaldı',
                'example_sentence_1' => 'Don\'t ask about it—let sleeping dogs lie.',
                'example_sentence_2' => 'Don\'t mention the fight—let sleeping dogs lie.',
                'image_path' => 'idioms/gorsel90.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Beat the clock',
                'turkish_translation' => 'Bir işi zamanı dolmadan başarmak',
                'example_sentence_1' => 'I beat the clock and finished the test on time.',
                'example_sentence_2' => 'I beat the clock and sent the email right before the deadline.',
                'image_path' => 'idioms/gorsel91.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Pick someone\'s brain',
                'turkish_translation' => 'Birinden fikir almak',
                'example_sentence_1' => 'Can I pick your brain about this topic?',
                'example_sentence_2' => 'I need to pick your brain about science homework.',
                'image_path' => 'idioms/gorsel92.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Get the ball rolling',
                'turkish_translation' => 'Bir şeye başlamak/Harekete geçmek',
                'example_sentence_1' => 'Let\'s get the ball rolling on this project.',
                'example_sentence_2' => 'Let\'s get the ball rolling on our group project.',
                'image_path' => 'idioms/gorsel93.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Hit a wall',
                'turkish_translation' => 'Toslamak/ Tıkanmak kalmak',
                'example_sentence_1' => 'I was doing fine until I hit a wall.',
                'example_sentence_2' => 'I was so tired, I hit a wall halfway through.',
                'image_path' => 'idioms/gorsel94.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'My lips are sealed',
                'turkish_translation' => 'Söz vermek/ Sır tutmak',
                'example_sentence_1' => 'Don\'t worry—my lips are sealed.',
                'example_sentence_2' => 'No worries—my lips are sealed like a vault.',
                'image_path' => 'idioms/gorsel95.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Put on a brave face',
                'turkish_translation' => 'Üzgünken bile dağ gibi durmaya çalışmak',
                'example_sentence_1' => 'She put on a brave face despite the bad news.',
                'example_sentence_2' => 'He smiled and put on a brave face after the bad news.',
                'image_path' => 'idioms/gorsel96.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'In the dark',
                'turkish_translation' => 'Bir konuda hiçbir bilgiye sahip olmamak',
                'example_sentence_1' => 'I was completely in the dark about their plans.',
                'example_sentence_2' => 'I felt completely in the dark during the meeting.',
                'image_path' => 'idioms/gorsel97.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Face the music',
                'turkish_translation' => 'Bedelini ödemek/ Yapılan hatanın sonuçlarına katlanmak',
                'example_sentence_1' => 'He broke the rule and now has to face the music.',
                'example_sentence_2' => 'You broke the rules—now it\'s time to face the music.',
                'image_path' => 'idioms/gorsel98.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Bite your tongue',
                'turkish_translation' => 'Bir şeyi içinde tutmak /söylememek',
                'example_sentence_1' => 'I wanted to argue, but I bit my tongue.',
                'example_sentence_2' => 'I wanted to yell, but I bit my tongue instead.',
                'image_path' => 'idioms/gorsel99.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ],
            [
                'english_phrase' => 'Slow and steady wins the race',
                'turkish_translation' => 'Yavaş ama kararlı olan kazanır',
                'example_sentence_1' => 'Don\'t rush—slow and steady wins the race.',
                'example_sentence_2' => 'He won the race because slow and steady wins the race.',
                'image_path' => 'idioms/gorsel100.jpg',
                'is_active' => true,
                'display_date' => Carbon::now(),
            ]
        ];

        DB::table('idioms')->insert($idioms);
    }
}